"""auto migration

Revision ID: e4a4cc8bd9ea
Revises: f47dc0da8cad
Create Date: 2025-11-22 01:29:07.126038

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e4a4cc8bd9ea'
down_revision: Union[str, Sequence[str], None] = 'f47dc0da8cad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('max_sodiums', sa.Float(), nullable=False))
    op.drop_column('users', 'max_sodium')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('max_sodium', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.drop_column('users', 'max_sodiums')
    # ### end Alembic commands ###
