"""auto migration

Revision ID: f5b5cd60d422
Revises: e82225374ff7
Create Date: 2025-11-23 14:33:31.655699

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f5b5cd60d422'
down_revision: Union[str, Sequence[str], None] = 'e82225374ff7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('occupations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('users', sa.Column('occupation_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'users', 'occupations', ['occupation_id'], ['id'])
    op.drop_column('users', 'occupation')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('occupation', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'occupation_id')
    op.drop_table('occupations')
    # ### end Alembic commands ###
